
import type { Metadata } from "next";
import localFont from "next/font/local";
import "@repo/config/styles"
import { SessionProvider } from "next-auth/react";
import ClientProvider from "./src/ClientProvider";
import Navbar from "./src/components/Dashboard/Navbar";
import { SignInModalProvider } from "./src/components/Dashboard/landing/SignInProvider";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientProvider>
          <Navbar/>
          <SignInModalProvider>
            {children}
          </SignInModalProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
